# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class conferma_credenziali(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(322, 311)
        Form.setStyleSheet("background-color: rgb(40, 39, 39);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 30, 121, 41))
        self.label.setStyleSheet("color: rgb(221, 215, 25);\n"
"font: 30pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 201, 20))
        self.label_2.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_2.setObjectName("label_2")
        self.label_Username = QtWidgets.QLabel(Form)
        self.label_Username.setGeometry(QtCore.QRect(50, 120, 81, 20))
        self.label_Username.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_Username.setObjectName("label_3")


        self.Inserimento_Username = QtWidgets.QPlainTextEdit(Form)
        self.Inserimento_Username.setGeometry(QtCore.QRect(50, 140, 221, 31))
        self.Inserimento_Username.setStyleSheet("background-color: rgb(207, 211, 211);\n"
"border-radius: 3px;")
        self.Inserimento_Username.setObjectName("plainTextEdit")


        self.label_Password = QtWidgets.QLabel(Form)
        self.label_Password.setGeometry(QtCore.QRect(50, 180, 81, 20))
        self.label_Password.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_Password.setObjectName("label_4")


        self.Inserimento_Password = QtWidgets.QPlainTextEdit(Form)
        self.Inserimento_Password.setGeometry(QtCore.QRect(50, 200, 221, 31))
        self.Inserimento_Password.setStyleSheet("background-color: rgb(207, 211, 211);\n"
"border-radius: 3px;")
        self.Inserimento_Password.setObjectName("plainTextEdit_2")


        self.btn_Back = QtWidgets.QPushButton(Form)
        self.btn_Back.setGeometry(QtCore.QRect(70, 260, 81, 21))
        self.btn_Back.setMouseTracking(True)
        self.btn_Back.setTabletTracking(True)
        self.btn_Back.setStyleSheet("*{border: 0.5px solid rgb(221, 215, 25);"
                                       "border-radius: 10px;\n"
                                       "font: 10pt \"Arial\";"
                                       "color: 'white';}" +
                                       "*:hover{background: rgb(221, 215, 25);\n}")
        self.btn_Back.setObjectName("pushButton_3")
        self.btn_Ok = QtWidgets.QPushButton(Form)
        self.btn_Ok.setGeometry(QtCore.QRect(170, 260, 81, 21))
        self.btn_Ok.setMouseTracking(True)
        self.btn_Ok.setTabletTracking(True)
        self.btn_Ok.setStyleSheet("*{border: 0.5px solid rgb(221, 215, 25);"
                                       "border-radius: 10px;\n"
                                       "font: 10pt \"Arial\";"
                                       "color: 'white';}" +
                                       "*:hover{background: rgb(221, 215, 25);\n}")
        self.btn_Ok.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PySound"))
        self.label_2.setText(_translate("Form", "Per confermare l\'eliminazione"))
        self.label_Username.setText(_translate("Form", "Username:"))
        self.label_Password.setText(_translate("Form", "Password:"))
        self.btn_Back.setText(_translate("Form", "Back"))
        self.btn_Ok.setText(_translate("Form", "Ok"))

"""app = QApplication([])
window = QWidget()
form = conferma_credenziali()
form.setupUi(window)
window.show()
app.exec()"""