# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Impostazioni.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class impostazioni(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(281, 311)
        Form.setStyleSheet("background-color: rgb(40, 39, 39);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 30, 121, 41))
        self.label.setStyleSheet("color: rgb(221, 215, 25);\n"
"font: 30pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 70, 81, 16))
        self.label_2.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 191, 16))
        self.label_3.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_3.setObjectName("label_3")
        self.btn_EliminaAccount = QtWidgets.QPushButton(Form)
        self.btn_EliminaAccount.setGeometry(QtCore.QRect(80, 190, 121, 31))
        self.btn_EliminaAccount.setMouseTracking(True)
        self.btn_EliminaAccount.setTabletTracking(True)
        self.btn_EliminaAccount.setStyleSheet("*{border: 0.5px solid rgb(221, 215, 25);"
                                       "border-radius: 10px;\n"
                                       "font: 10pt \"Arial\";"
                                       "color: 'white';}" +
                                       "*:hover{background: rgb(221, 215, 25);\n}")
        self.btn_EliminaAccount.setObjectName("pushButton")
        self.btn_EditProfilo = QtWidgets.QPushButton(Form)
        self.btn_EditProfilo.setGeometry(QtCore.QRect(80, 240, 121, 31))
        self.btn_EditProfilo.setMouseTracking(True)
        self.btn_EditProfilo.setTabletTracking(True)
        self.btn_EditProfilo.setStyleSheet("*{border: 0.5px solid rgb(221, 215, 25);"
                                       "border-radius: 10px;\n"
                                       "font: 10pt \"Arial\";"
                                       "color: 'white';}" +
                                       "*:hover{background: rgb(221, 215, 25);\n}")
        self.btn_EditProfilo.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PySound"))
        self.label_2.setText(_translate("Form", "Impostazioni"))
        self.label_3.setText(_translate("Form", "Tipo di account: **tipo**"))
        self.btn_EliminaAccount.setText(_translate("Form", "Elimina account"))
        self.btn_EditProfilo.setText(_translate("Form", "Edit profilo"))


"""app = QApplication([])
window = QWidget()
form = impostazioni()
form.setupUi(window)
window.show()
app.exec()"""