# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyLemon_easter_egg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize, Qt
from PyQt5.QtGui import QIcon, QMovie
from PyQt5.QtWidgets import QApplication, QWidget


class Easter_egg(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 370)
        Form.setStyleSheet("background-color: rgb(40, 39, 39);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 30, 141, 51))
        self.label.setStyleSheet("color: rgb(221, 215, 25);\n"
"font: 30pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")


        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 200, 141, 21))
        self.label_3.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(150, 230, 101, 21))
        self.label_4.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(150, 250, 121, 21))
        self.label_5.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(140, 270, 121, 21))
        self.label_6.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(140, 290, 111, 20))
        self.label_7.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(138, 330, 150, 16))
        self.label_8.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_8.setObjectName("label_8")

        '''self.btn_limone = QtWidgets.QPushButton(Form)
        self.btn_limone.setGeometry(QtCore.QRect(160, 20, 81, 130))
        font = QtGui.QFont()
        self.btn_limone.setFont(font)
        self.btn_limone.setStyleSheet("*{border: 0.5px solid rgb(40, 39, 39);"  # border per i bordi
                                      "border-radius: 25px;\n"
                                      "font: 10pt \"Arial\";"
                                      "color: 'white';}")
        self.btn_limone.setText("")
        self.btn_limone.setObjectName("btn_limone")
        self.btn_limone.setIcon(QIcon('Limone.png'))
        self.btn_limone.setIconSize(QtCore.QSize(170, 170))'''

        '''--------Animazione Limone--------'''

        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.gif_label = QtWidgets.QLabel(self.centralwidget)
        self.gif_label.setGeometry(QtCore.QRect(80, 0, 140, 250))
        self.gif_label.setMinimumSize(QtCore.QSize(300, 200))
        self.gif_label.setMaximumSize(QtCore.QSize(300, 200))

        self.gif_label.setObjectName("gif")
        self.movie = QMovie("Limone-gif-unscreen.gif")
        self.movie.setScaledSize(QSize().scaled(400, 250, Qt.KeepAspectRatio))
        self.gif_label.setMovie(self.movie)
        self.movie.start()



        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", ""))
        self.label.setText(_translate("Form", ""))
        self.label_3.setText(_translate("Form", "       LemonCreatori:"))
        self.label_4.setText(_translate("Form", "    André Mazzi"))
        self.label_5.setText(_translate("Form", "   Andrea Tassi"))
        self.label_6.setText(_translate("Form", "    Manuel Mariotti"))
        self.label_7.setText(_translate("Form", "    Stefano Martelli"))
        self.label_8.setText(_translate("Form", "  LemonVersion: 1.0"))
        #self.btn_limone.setText(_translate("Form", ""))


'''app = QApplication([])
window = QWidget()
form = Easter_egg()
form.setupUi(window)
window.show()
app.exec()'''
