# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class upgrade_da_ascoltatore(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 261)
        Form.setStyleSheet("background-color: rgb(40, 39, 39);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 20, 121, 41))
        self.label.setStyleSheet("color: rgb(221, 215, 25);\n"
"font: 30pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 60, 171, 16))
        self.label_2.setStyleSheet("color: rgb(207, 211, 211);")
        self.label_2.setObjectName("label_2")
        self.btn_artista = QtWidgets.QPushButton(Form)
        self.btn_artista.setGeometry(QtCore.QRect(140, 110, 121, 31))
        self.btn_artista.setMouseTracking(True)
        self.btn_artista.setTabletTracking(True)
        self.btn_artista.setStyleSheet("*{border: 0.5px solid rgb(221, 215, 25);"   #border per i bordi
                                       "border-radius: 10px;\n"
                                       "font: 10pt \"Arial\";"
                                       "color: 'white';}" +
                                       "*:hover{background: rgb(221, 215, 25);\n}")
        self.btn_artista.setObjectName("pushButton")
        self.btn_etichetta = QtWidgets.QPushButton(Form)
        self.btn_etichetta.setGeometry(QtCore.QRect(140, 170, 121, 31))
        self.btn_etichetta.setMouseTracking(True)
        self.btn_etichetta.setTabletTracking(True)
        self.btn_etichetta.setStyleSheet("*{border: 0.5px solid rgb(221, 215, 25);"   #border per i bordi
                                         "border-radius: 10px;\n"
                                       "font: 10pt \"Arial\";"
                                       "color: 'white';}" +
                                       "*:hover{background: rgb(221, 215, 25);\n}")
        self.btn_etichetta.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PySound"))
        self.label_2.setText(_translate("Form", "Scegli il tuo nuovo account"))
        self.btn_artista.setText(_translate("Form", "Artista"))
        self.btn_etichetta.setText(_translate("Form", "Etichetta"))

app = QApplication([])
window = QWidget()
form = upgrade_da_ascoltatore()
form.setupUi(window)
window.show()
app.exec()